project:
  type: website

website:
  title: "Development of Chess Computers Across Decades"
  navbar:
    left:
      - href: page0.qmd
        text: Home
      - page1.qmd
      - page2.qmd
      - page3.qmd
      - page4.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



